/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ordemProducao.consultas;

import connection.ConnectionFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author 1113778771
 */
public class EnviarArquivo extends javax.swing.JInternalFrame {

    /**
     * Creates new form EnviarArquivo
     */
    private int codOp = 0;
    private byte tipoVersao = (byte) 0;

    public static EnviarArquivo getInstancia(int codOp, byte tipoVersao){
        return new EnviarArquivo(codOp, tipoVersao);
    }

    public EnviarArquivo(int codOp, byte tipoVersao) {
        initComponents();
        this.codOp = codOp;
        this.tipoVersao = tipoVersao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seletorDeArquivos = new javax.swing.JFileChooser();
        enviarEstoque = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        enderecoArquivo = new javax.swing.JLabel();

        setTitle("ENVIAR ARQUIVO");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/upload.png"))); // NOI18N

        seletorDeArquivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seletorDeArquivosMouseClicked(evt);
            }
        });
        seletorDeArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletorDeArquivosActionPerformed(evt);
            }
        });

        enviarEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/upload.png"))); // NOI18N
        enviarEstoque.setText("UPLOAD");
        enviarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarEstoqueActionPerformed(evt);
            }
        });

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancelar.png"))); // NOI18N
        cancelar.setText("CANCELAR");

        enderecoArquivo.setText("ARQUIVO SELECIONADO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seletorDeArquivos, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enderecoArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviarEstoque)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(seletorDeArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarEstoque)
                    .addComponent(cancelar)
                    .addComponent(enderecoArquivo))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancelar, enderecoArquivo});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seletorDeArquivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seletorDeArquivosMouseClicked

    }//GEN-LAST:event_seletorDeArquivosMouseClicked

    private void seletorDeArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorDeArquivosActionPerformed
        if (seletorDeArquivos.getSelectedFile() != null) {
            enderecoArquivo.setText("ARQUIVO SELECIONADO: " + seletorDeArquivos.getSelectedFile().getPath().toString());
        }
    }//GEN-LAST:event_seletorDeArquivosActionPerformed

    private void enviarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarEstoqueActionPerformed
        new Thread() {
            @Override
            public void run() {
                if (ConnectionFactory.uploadArquivo(String.valueOf(codOp), tipoVersao, seletorDeArquivos.getSelectedFile().getPath())) {
                    JOptionPane.showMessageDialog(null, "ARQUIVO ENVIADO COM SUCESSO!", "AVISO", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }
        }.start();
    }//GEN-LAST:event_enviarEstoqueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel enderecoArquivo;
    private javax.swing.JButton enviarEstoque;
    private javax.swing.JFileChooser seletorDeArquivos;
    // End of variables declaration//GEN-END:variables
}
