/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ordemProducao.consultas;

import javax.swing.JLabel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.dao.ArquivosDAO;
import ui.controle.Controle;

/**
 *
 * @author 1113778771
 */
public class EnviarArquivo extends javax.swing.JInternalFrame {

    /**
     * Creates new form EnviarArquivo
     */
    private int codOp = 0;
    private byte tipoVersao = (byte) 0;
    private JLabel loading;
    FileFilter filter = new FileNameExtensionFilter("Arquivos compactados - .zip", "zip");

    public static EnviarArquivo getInstancia(int codOp, byte tipoVersao, JLabel loading) {
        return new EnviarArquivo(codOp, tipoVersao, loading);
    }

    public EnviarArquivo(int codOp, byte tipoVersao, JLabel loading) {
        initComponents();
        this.codOp = codOp;
        this.tipoVersao = tipoVersao;
        this.loading = loading;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seletorDeArquivos = new javax.swing.JFileChooser();
        enviarArquivo = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        enderecoArquivo = new javax.swing.JLabel();

        setTitle("ENVIAR ARQUIVO");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/upload.png"))); // NOI18N

        seletorDeArquivos.setAcceptAllFileFilterUsed(false);
        seletorDeArquivos.setFileFilter(filter);
        seletorDeArquivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seletorDeArquivosMouseClicked(evt);
            }
        });
        seletorDeArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seletorDeArquivosActionPerformed(evt);
            }
        });

        enviarArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/upload.png"))); // NOI18N
        enviarArquivo.setText("UPLOAD");
        enviarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarArquivoActionPerformed(evt);
            }
        });

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancelar.png"))); // NOI18N
        cancelar.setText("CANCELAR");

        enderecoArquivo.setText("ARQUIVO SELECIONADO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seletorDeArquivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enderecoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviarArquivo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(seletorDeArquivos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarArquivo)
                    .addComponent(cancelar)
                    .addComponent(enderecoArquivo))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancelar, enderecoArquivo});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seletorDeArquivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seletorDeArquivosMouseClicked

    }//GEN-LAST:event_seletorDeArquivosMouseClicked

    private void seletorDeArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seletorDeArquivosActionPerformed
        if (seletorDeArquivos.getSelectedFile() != null) {
            enderecoArquivo.setText("ARQUIVO SELECIONADO: " + seletorDeArquivos.getSelectedFile().getPath().toString());
        }
    }//GEN-LAST:event_seletorDeArquivosActionPerformed

    private void enviarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarArquivoActionPerformed
        new Thread("Upload Arquivo") {
            @Override
            public void run() {
                if (ArquivosDAO.uploadArquivo(String.valueOf(codOp),
                        tipoVersao,
                        seletorDeArquivos.getSelectedFile().getPath(),
                        seletorDeArquivos.getSelectedFile().getPath().substring(seletorDeArquivos.getSelectedFile().getPath().indexOf(".")),
                        loading)) {
                    Controle.avisosUsuario((byte) 2, "UPLOAD FEITO COM SUCESSO.");
                    loading.setVisible(false);
                }else{
                    loading.setVisible(false);
                }
            }
        }.start();
    }//GEN-LAST:event_enviarArquivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel enderecoArquivo;
    private javax.swing.JButton enviarArquivo;
    private javax.swing.JFileChooser seletorDeArquivos;
    // End of variables declaration//GEN-END:variables
}
